classDiagram
direction TB

class Persona {
    -__rut: str
    -__nombre: str
    -__telefono_movil: str
    +validar_datos(): bool
}

class Cliente {
    -__id_cliente: int
    -__pasaporte: str
    -__correo: str
    +validar_pasaporte(): bool
}

class Paquete_Turistico {
    -__codigo: int
    -__nombre: str
    -__duracion: int
    -__precio_base: float
    +calcular_precio(tasa_cambio: float = None): float
    +obtener_detalle(): str
}

class Paquete_Nacional {
    +calcular_precio(tasa_cambio: float = None): float
}

class Paquete_Internacional {
    -__pasaporte_valido: bool
    +calcular_precio(tasa_cambio: float = None): float
}

class Paquete_Crucero {
    -__impuesto_puerto: float
    +calcular_precio(tasa_cambio: float = None): float
}

class Reserva {
    -__numero_reserva: str
    -__fecha_reserva: date
    -__fecha_viaje: date
    -__estado: str
    -__tasa_cambio_aplicada: float
    -__cliente: Cliente
    -__paquete: Paquete_Turistico
    -__detalles: list[Detalle_Reserva]
    +agregar_detalle(cantidad: int): Detalle_Reserva
    +validar_anticipo(monto_anticipo: float): bool
    +calcular_total(): float
    +confirmar(): bool
    +cancelar(): bool
}

class Detalle_Reserva {
    -__id_detalle: int
    -__paquete: Paquete_Turistico
    -__tasa_cambio: float
    -__cantidad: int
    -__subtotal: float
    +calcular_subtotal(): float
}

class Pago {
    -__id_pago: str
    -__fecha: date
    -__monto: float
    -__estado: str
    -__fecha_vencimiento: date
    -__reserva: Reserva
    -__boleta: Boleta
    +procesar_pago(): None
}

class Boleta {
    -__num_boleta: int
    -__fecha: date
    -__monto: float
    -__emitida: bool
    +emitir(): None
}

Persona <|-- Cliente
Paquete_Turistico <|-- Paquete_Nacional
Paquete_Turistico <|-- Paquete_Internacional
Paquete_Turistico <|-- Paquete_Crucero
Cliente "1" o-- "0..*" Reserva : cliente existente
Reserva "0..*" o-- "1" Paquete_Turistico : paquete existente
Reserva "1" *-- "0..*" Detalle_Reserva : compone
Pago "1" *-- "1" Boleta : compone
